package com.tns.mes.identity.web;

import com.tns.mes.common.api.ApiResponse;
import com.tns.mes.identity.domain.DataDictionary;
import com.tns.mes.identity.domain.MenuItem;
import com.tns.mes.identity.domain.MenuField;
import com.tns.mes.identity.domain.MenuAction;
import com.tns.mes.identity.repo.DataDictionaryRepository;
import com.tns.mes.identity.repo.MenuItemRepository;
import com.tns.mes.identity.repo.MenuFieldRepository;
import com.tns.mes.identity.repo.MenuActionRepository;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/v1/system")
public class SystemConfigController {
    private final MenuItemRepository menus; private final DataDictionaryRepository dictionaries;
    private final MenuFieldRepository fields; private final MenuActionRepository actions;
    public SystemConfigController(MenuItemRepository menus, DataDictionaryRepository dictionaries, MenuFieldRepository fields, MenuActionRepository actions){this.menus=menus;this.dictionaries=dictionaries;this.fields=fields;this.actions=actions;}
    @GetMapping("/menus") public ApiResponse<List<MenuView>> menuList(HttpServletRequest r){return ApiResponse.ok(menus.findAll().stream().sorted(Comparator.comparing(MenuItem::getSortOrder).thenComparing(MenuItem::getCode)).map(MenuView::new).collect(Collectors.toList()), id(r));}
    @PostMapping("/menus") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<MenuView> menuCreate(@Valid @RequestBody MenuRequest b,HttpServletRequest r){if(menus.findByCode(b.code).isPresent()) throw new IllegalArgumentException("Duplicate menu code"); MenuItem m=apply(new MenuItem(),b); return ApiResponse.ok(new MenuView(menus.save(m)),id(r));}
    @PutMapping("/menus/{id}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<MenuView> menuUpdate(@PathVariable Long id,@Valid @RequestBody MenuRequest b,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow(); return ApiResponse.ok(new MenuView(menus.save(apply(m,b))),id(r));}
    @DeleteMapping("/menus/{id}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<Void> menuDelete(@PathVariable Long id,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow();m.setStatus("INACTIVE");menus.save(m);return ApiResponse.ok(null,id(r));}
    @GetMapping("/menus/{id}/config") public ApiResponse<MenuConfigView> menuConfig(@PathVariable Long id,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow();return ApiResponse.ok(new MenuConfigView(m,fields.findByMenuCodeOrderBySortOrderAsc(m.getCode()),actions.findByMenuCodeOrderBySortOrderAsc(m.getCode())),id(r));}
    @GetMapping("/menus/{id}/fields") public ApiResponse<List<FieldView>> fieldList(@PathVariable Long id,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow();return ApiResponse.ok(fields.findByMenuCodeOrderBySortOrderAsc(m.getCode()).stream().map(FieldView::new).collect(Collectors.toList()),id(r));}
    @PostMapping("/menus/{id}/fields") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<FieldView> fieldCreate(@PathVariable Long id,@Valid @RequestBody FieldRequest b,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow();MenuField f=apply(new MenuField(),b,m.getCode());return ApiResponse.ok(new FieldView(fields.save(f)),id(r));}
    @PutMapping("/menu-fields/{fieldId}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<FieldView> fieldUpdate(@PathVariable Long fieldId,@Valid @RequestBody FieldRequest b,HttpServletRequest r){MenuField f=fields.findById(fieldId).orElseThrow();return ApiResponse.ok(new FieldView(fields.save(apply(f,b,f.getMenuCode()))),id(r));}
    @DeleteMapping("/menu-fields/{fieldId}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<Void> fieldDelete(@PathVariable Long fieldId,HttpServletRequest r){MenuField f=fields.findById(fieldId).orElseThrow();f.setStatus("INACTIVE");fields.save(f);return ApiResponse.ok(null,id(r));}
    @GetMapping("/menus/{id}/actions") public ApiResponse<List<ActionView>> actionList(@PathVariable Long id,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow();return ApiResponse.ok(actions.findByMenuCodeOrderBySortOrderAsc(m.getCode()).stream().map(ActionView::new).collect(Collectors.toList()),id(r));}
    @PostMapping("/menus/{id}/actions") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<ActionView> actionCreate(@PathVariable Long id,@Valid @RequestBody ActionRequest b,HttpServletRequest r){MenuItem m=menus.findById(id).orElseThrow();MenuAction a=apply(new MenuAction(),b,m.getCode());return ApiResponse.ok(new ActionView(actions.save(a)),id(r));}
    @PutMapping("/menu-actions/{actionId}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<ActionView> actionUpdate(@PathVariable Long actionId,@Valid @RequestBody ActionRequest b,HttpServletRequest r){MenuAction a=actions.findById(actionId).orElseThrow();return ApiResponse.ok(new ActionView(actions.save(apply(a,b,a.getMenuCode()))),id(r));}
    @DeleteMapping("/menu-actions/{actionId}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<Void> actionDelete(@PathVariable Long actionId,HttpServletRequest r){MenuAction a=actions.findById(actionId).orElseThrow();a.setStatus("INACTIVE");actions.save(a);return ApiResponse.ok(null,id(r));}
    @GetMapping("/dictionaries") public ApiResponse<List<DictView>> dictList(@RequestParam(required=false) String type,HttpServletRequest r){List<DataDictionary> all=type==null||type.trim().isEmpty()?dictionaries.findAll():dictionaries.findByDictTypeOrderBySortOrderAsc(type.trim());return ApiResponse.ok(all.stream().sorted(Comparator.comparing(DataDictionary::getSortOrder).thenComparing(DataDictionary::getDictType)).map(DictView::new).collect(Collectors.toList()),id(r));}
    @PostMapping("/dictionaries") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<DictView> dictCreate(@Valid @RequestBody DictRequest b,HttpServletRequest r){return ApiResponse.ok(new DictView(dictionaries.save(apply(new DataDictionary(),b))),id(r));}
    @PutMapping("/dictionaries/{id}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<DictView> dictUpdate(@PathVariable Long id,@Valid @RequestBody DictRequest b,HttpServletRequest r){DataDictionary d=dictionaries.findById(id).orElseThrow();return ApiResponse.ok(new DictView(dictionaries.save(apply(d,b))),id(r));}
    @DeleteMapping("/dictionaries/{id}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<Void> dictDelete(@PathVariable Long id,HttpServletRequest r){DataDictionary d=dictionaries.findById(id).orElseThrow();d.setStatus("INACTIVE");dictionaries.save(d);return ApiResponse.ok(null,id(r));}
    @PutMapping("/dictionaries/type/{oldType}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<Integer> dictTypeRename(@PathVariable String oldType,@RequestBody DictTypeRenameRequest b,HttpServletRequest r){List<DataDictionary> items=dictionaries.findByDictTypeOrderBySortOrderAsc(oldType);items.forEach(d->d.setDictType(b.newType.trim()));dictionaries.saveAll(items);return ApiResponse.ok(items.size(),id(r));}
    @DeleteMapping("/dictionaries/type/{type}") @PreAuthorize("hasAuthority('USER_ADMIN')") public ApiResponse<Integer> dictTypeDelete(@PathVariable String type,HttpServletRequest r){List<DataDictionary> items=dictionaries.findByDictTypeOrderBySortOrderAsc(type);items.forEach(d->d.setStatus("INACTIVE"));dictionaries.saveAll(items);return ApiResponse.ok(items.size(),id(r));}
    private MenuItem apply(MenuItem m,MenuRequest b){m.setCode(b.code.trim());m.setNameZh(b.nameZh.trim());m.setNameEn(b.nameEn);m.setNameAr(b.nameAr);m.setParentCode(b.parentCode);m.setPath(b.path);m.setIcon(b.icon);m.setPermissionCode(b.permissionCode);m.setSortOrder(b.sortOrder==null?0:b.sortOrder);m.setStatus(b.status==null?"ACTIVE":b.status);return m;}
    private DataDictionary apply(DataDictionary d,DictRequest b){d.setDictType(b.dictType.trim());d.setDictCode(b.dictCode.trim());d.setLabelZh(b.labelZh.trim());d.setLabelEn(b.labelEn);d.setLabelAr(b.labelAr);d.setDictValue(b.dictValue.trim());d.setSortOrder(b.sortOrder==null?0:b.sortOrder);d.setStatus(b.status==null?"ACTIVE":b.status);return d;}
    private MenuField apply(MenuField f,FieldRequest b,String menuCode){f.setMenuCode(menuCode);f.setFieldCode(b.fieldCode.trim());f.setFieldPath(b.fieldPath.trim());f.setLabelZh(b.labelZh.trim());f.setLabelEn(b.labelEn);f.setLabelAr(b.labelAr);f.setFieldType(b.fieldType==null?"TEXT":b.fieldType);f.setVisibleList(b.visibleList==null||b.visibleList);f.setVisibleDetail(b.visibleDetail==null||b.visibleDetail);f.setQueryable(Boolean.TRUE.equals(b.queryable));f.setDefaultVisible(b.defaultVisible==null||b.defaultVisible);f.setSortOrder(b.sortOrder==null?0:b.sortOrder);f.setStatus(b.status==null?"ACTIVE":b.status);return f;}
    private MenuAction apply(MenuAction a,ActionRequest b,String menuCode){a.setMenuCode(menuCode);a.setActionCode(b.actionCode.trim());a.setNameZh(b.nameZh.trim());a.setNameEn(b.nameEn);a.setNameAr(b.nameAr);a.setActionType(b.actionType==null?"BUTTON":b.actionType);a.setPermissionCode(b.permissionCode.trim());a.setSortOrder(b.sortOrder==null?0:b.sortOrder);a.setStatus(b.status==null?"ACTIVE":b.status);return a;}
    private String id(HttpServletRequest r){Object v=r.getAttribute("requestId");return v==null?null:v.toString();}
    public static class MenuRequest { @javax.validation.constraints.NotBlank public String code; @javax.validation.constraints.NotBlank public String nameZh; public String nameEn,nameAr,parentCode,path,icon,permissionCode,status; public Integer sortOrder; }
    public static class DictRequest { @javax.validation.constraints.NotBlank public String dictType,dictCode,labelZh,dictValue; public String labelEn,labelAr,status; public Integer sortOrder; }
    public static class DictTypeRenameRequest { @javax.validation.constraints.NotBlank public String newType; public String newLabel; }
    public static class FieldRequest { @javax.validation.constraints.NotBlank public String fieldCode,fieldPath,labelZh; public String labelEn,labelAr,fieldType,status; public Boolean visibleList,visibleDetail,queryable,defaultVisible; public Integer sortOrder; }
    public static class ActionRequest { @javax.validation.constraints.NotBlank public String actionCode,nameZh,permissionCode; public String nameEn,nameAr,actionType,status; public Integer sortOrder; }
    public static class MenuView { public Long id; public String code,nameZh,nameEn,nameAr,parentCode,path,icon,permissionCode,status; public Integer sortOrder; MenuView(MenuItem m){id=m.getId();code=m.getCode();nameZh=m.getNameZh();nameEn=m.getNameEn();nameAr=m.getNameAr();parentCode=m.getParentCode();path=m.getPath();icon=m.getIcon();permissionCode=m.getPermissionCode();status=m.getStatus();sortOrder=m.getSortOrder();} public Long getId(){return id;} public String getCode(){return code;} public String getNameZh(){return nameZh;} public String getNameEn(){return nameEn;} public String getNameAr(){return nameAr;} public String getParentCode(){return parentCode;} public String getPath(){return path;} public String getIcon(){return icon;} public String getPermissionCode(){return permissionCode;} public String getStatus(){return status;} public Integer getSortOrder(){return sortOrder;} }
    public static class DictView { public Long id; public String dictType,dictCode,labelZh,labelEn,labelAr,dictValue,status; public Integer sortOrder; DictView(DataDictionary d){id=d.getId();dictType=d.getDictType();dictCode=d.getDictCode();labelZh=d.getLabelZh();labelEn=d.getLabelEn();labelAr=d.getLabelAr();dictValue=d.getDictValue();status=d.getStatus();sortOrder=d.getSortOrder();} public Long getId(){return id;} public String getDictType(){return dictType;} public String getDictCode(){return dictCode;} public String getLabelZh(){return labelZh;} public String getLabelEn(){return labelEn;} public String getLabelAr(){return labelAr;} public String getDictValue(){return dictValue;} public String getStatus(){return status;} public Integer getSortOrder(){return sortOrder;} }
    public static class FieldView { public Long id; public String menuCode,fieldCode,fieldPath,labelZh,labelEn,labelAr,fieldType,status; public Boolean visibleList,visibleDetail,queryable,defaultVisible; public Integer sortOrder; FieldView(MenuField f){id=f.getId();menuCode=f.getMenuCode();fieldCode=f.getFieldCode();fieldPath=f.getFieldPath();labelZh=f.getLabelZh();labelEn=f.getLabelEn();labelAr=f.getLabelAr();fieldType=f.getFieldType();visibleList=f.getVisibleList();visibleDetail=f.getVisibleDetail();queryable=f.getQueryable();defaultVisible=f.getDefaultVisible();sortOrder=f.getSortOrder();status=f.getStatus();} public Long getId(){return id;} public String getMenuCode(){return menuCode;} public String getFieldCode(){return fieldCode;} public String getFieldPath(){return fieldPath;} public String getLabelZh(){return labelZh;} public String getLabelEn(){return labelEn;} public String getLabelAr(){return labelAr;} public String getFieldType(){return fieldType;} public Boolean getVisibleList(){return visibleList;} public Boolean getVisibleDetail(){return visibleDetail;} public Boolean getQueryable(){return queryable;} public Boolean getDefaultVisible(){return defaultVisible;} public Integer getSortOrder(){return sortOrder;} public String getStatus(){return status;} }
    public static class ActionView { public Long id; public String menuCode,actionCode,nameZh,nameEn,nameAr,actionType,permissionCode,status; public Integer sortOrder; ActionView(MenuAction a){id=a.getId();menuCode=a.getMenuCode();actionCode=a.getActionCode();nameZh=a.getNameZh();nameEn=a.getNameEn();nameAr=a.getNameAr();actionType=a.getActionType();permissionCode=a.getPermissionCode();sortOrder=a.getSortOrder();status=a.getStatus();} public Long getId(){return id;} public String getMenuCode(){return menuCode;} public String getActionCode(){return actionCode;} public String getNameZh(){return nameZh;} public String getNameEn(){return nameEn;} public String getNameAr(){return nameAr;} public String getActionType(){return actionType;} public String getPermissionCode(){return permissionCode;} public Integer getSortOrder(){return sortOrder;} public String getStatus(){return status;} }
    public static class MenuConfigView { public MenuView menu; public List<FieldView> fields; public List<ActionView> actions; MenuConfigView(MenuItem m,List<MenuField> fs,List<MenuAction> as){menu=new MenuView(m);fields=fs.stream().map(FieldView::new).collect(Collectors.toList());actions=as.stream().map(ActionView::new).collect(Collectors.toList());} public MenuView getMenu(){return menu;} public List<FieldView> getFields(){return fields;} public List<ActionView> getActions(){return actions;} }
}
